# Generated by Django 4.1.6 on 2023-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS', 'Anonym chat'), ('FIGURE', 'Figure chat'), ('PLAYER', 'Player chat')], max_length=30),
        ),
    ]
