# Generated by Django 4.1.6 on 2023-04-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_profile'),
        ('chat', '0002_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
            preserve_default=False,
        ),
    ]
