# Generated by Django 4.1.6 on 2023-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_figure_description_alter_figure_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figure',
            name='figure_set',
        ),
        migrations.AlterField(
            model_name='figure',
            name='type',
            field=models.CharField(choices=[('PROFESSION', 'Profession'), ('PERSONA', 'Persona'), ('ALONE', 'Alone')], help_text='What kind of figure is this?', max_length=20),
        ),
        migrations.AddField(
            model_name='figure',
            name='figure_set',
            field=models.ManyToManyField(blank=True, null=True, to='game.figureset'),
        ),
    ]
