# Generated by Django 4.1.6 on 2023-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_figure_figure_set_alter_figure_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='figure_set',
            field=models.ManyToManyField(blank=True, to='game.figureset'),
        ),
    ]
