# Generated by Django 4.1.6 on 2023-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_player_figure_set_alter_player_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.ImageField(blank=True, help_text='Vilken profilbild vill du ha i spelet?', null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
