# Generated by Django 4.1.6 on 2023-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile',
            field=models.ImageField(help_text='Vilken profilbild vill du ha i spelet?', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
